import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    productBrand: "Tata Tea",
    productDetail: "Desh Ki Chai",
    originalPrice: 499,
    price: 410,
    discount: 17,
    ratings: 3.7,
    inStock: true,
    fastDelivery: false,
    imgURL: "../assets/tata-tea-normal.jpg",
    category: "normal",
  },
  {
    id: 2,
    productBrand: "Tata Tea Gold",
    productDetail: "Real Taste Incredible Aroma",
    originalPrice: 530,
    price: 450,
    discount: 15,
    ratings: 4.1,
    inStock: false,
    fastDelivery: true,
    imgURL: "../assets/exotica-lemon-tea.jpg",
    category: "normal",
  },
  {
    id: 3,
    productBrand: "Taj Mahal Tea",
    productDetail:
      "Rich and Flavourful Chai - Premium Blend of Powdered Fresh Loose Tea Leaves",
    originalPrice: 395,
    price: 348,
    discount: 12,
    ratings: 2.7,
    inStock: true,
    fastDelivery: false,
    imgURL: "../assets/tajmahal-tea.jpg",
    category: "normal",
  },
  {
    id: 4,
    productBrand: "Exotica Tea",
    productDetail: "Easy to make and flavorful",
    originalPrice: 150,
    price: 125,
    discount: 16,
    ratings: 3.9,
    inStock: true,
    fastDelivery: true,
    imgURL: "../assets/flavored.png",
    category: "premium",
  },
  {
    id: 5,
    productBrand: "1868 Brew by Tata",
    productDetail: "",
    originalPrice: 1500,
    price: 1050,
    discount: 30,
    ratings: 4.8,
    inStock: true,
    fastDelivery: false,
    imgURL: "../assets/tajmahal-tea.jpg",
    category: "premium",
  },
  {
    id: 6,
    productBrand: "Adidas",
    productDetail: "Runesy M Running Shoes For Men  (Grey) ",
    originalPrice: 1000,
    price: 599,
    discount: 20,
    ratings: 2.0,
    inStock: false,
    fastDelivery: false,
    imgURL: "../assets/tajmahal-tea.jpg",
    category: "healthy",
  },
  {
    id: 7,
    productBrand: "Adidas",
    productDetail: "Pictoris M Running Shoes For Men  (Black) ",
    originalPrice: 2000,
    price: 1700,
    discount: 40,
    ratings: 3.0,
    inStock: true,
    fastDelivery: false,
    imgURL: "../assets/tajmahal-tea.jpg",
    category: "exotic",
  },
  // {
  //   id: 8,
  //   productBrand: "Adidas",
  //   productDetail: "Adifloss M Running Shoes For Men  (Blue) ",
  //   originalPrice: 5000,
  //   price: 2500,
  //   discount: 50,
  //   ratings: 2.9,
  //   inStock: false,
  //   fastDelivery: false,
  // },
  // {
  //   id: 9,
  //   productBrand: "Adidas",
  //   productDetail: "Quickflow M Running Shoes For Men  (Blue)",
  //   originalPrice: 9000,
  //   price: 8000,
  //   discount: 10,
  //   ratings: 4.9,
  //   inStock: false,
  //   fastDelivery: true,
  // },
  // {
  //   id: 10,
  //   productBrand: "Nike",
  //   productDetail: "Revolution 5 Running Shoes For Men  (Black) ",
  //   originalPrice: 2700,
  //   price: 2200,
  //   discount: 20,
  //   ratings: 2.8,
  //   inStock: false,
  //   fastDelivery: false,
  // },
  // {
  //   id: 11,
  //   productBrand: "Nike",
  //   productDetail: "Revolution 6 Next Nature Road s Running Shoes For Men  ",
  //   originalPrice: 9000,
  //   price: 8400,
  //   discount: 10,
  //   ratings: 4.9,
  //   inStock: true,
  //   fastDelivery: false,
  // },
  // {
  //   id: 12,
  //   productBrand: "Nike",
  //   productDetail: "Downshifter 11 Road s Running Shoes For Men ",
  //   originalPrice: 3000,
  //   price: 2000,
  //   discount: 30,
  //   ratings: 3.5,
  //   inStock: true,
  //   fastDelivery: true,
  // },
  // {
  //   id: 13,
  //   productBrand: "Nike",
  //   productDetail: "Revolution 4 Running Shoes For Men  (Black)",
  //   originalPrice: 7000,
  //   price: 5999,
  //   discount: 20,
  //   ratings: 3.9,
  //   inStock: true,
  //   fastDelivery: false,
  // },
  // {
  //   id: 14,
  //   productBrand: "Nike",
  //   productDetail: "Revolution 6 Next Nature Road Running Shoes",
  //   originalPrice: 5000,
  //   price: 3000,
  //   discount: 50,
  //   ratings: 3.1,
  //   inStock: false,
  //   fastDelivery: true,
  // },
  // {
  //   id: 15,
  //   productBrand: "Reebok",
  //   productDetail: "Downshifter 11 Road s Running Shoes For Men ",
  //   originalPrice: 10000,
  //   price: 9000,
  //   discount: 30,
  //   ratings: 3.5,
  //   inStock: true,
  //   fastDelivery: true,
  // },
  // {
  //   id: 16,
  //   productBrand: "Reebok",
  //   productDetail: "Revolution 4 Running Shoes For Men  (Black)",
  //   originalPrice: 10000,
  //   price: 8999,
  //   discount: 20,
  //   ratings: 3.9,
  //   inStock: true,
  //   fastDelivery: false,
  // },
  // {
  //   id: 17,
  //   productBrand: "Hrx",
  //   productDetail: "Revolution 6 Next Nature Road Running Shoes",
  //   originalPrice: 5000,
  //   price: 10000,
  //   discount: 50,
  //   ratings: 3.1,
  //   inStock: false,
  //   fastDelivery: true,
  // },
];
// export const products = [
//   {
//     _id: uuid(),
//     title: "You Can WIN",
//     author: "Shiv Khera",
//     price: "5000",
//     categoryName: "non-fiction",
//   },
//   {
//     _id: uuid(),
//     title: "You are Winner",
//     author: "Junaid Qureshi",
//     price: "3000",
//     categoryName: "horror",
//   },
//   {
//     _id: uuid(),
//     title: "Think and Grow Rich",
//     author: "Shiv Khera",
//     price: "1000",
//     categoryName: "fiction",
//   },
// ];
