import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    id: 1,
    productBrand: "Puma",
    productDetail: "Fire run running shoes for men",
    originalPrice: 2000,
    price: 1500,
    discount: 44,
    ratings: 4.7,
    inStock: true,
    fastDelivery: false,
    imgURL: "../assets/exotic.png",
  },
  {
    id: 2,
    productBrand: "Puma",
    productDetail: "Hustle V2 Running Shoes For Men  ",
    originalPrice: 3000,
    price: 2300,
    discount: 40,
    ratings: 4.1,
    inStock: false,
    fastDelivery: true,
    imgURL: "../assets/exotic.png",
  },
  {
    id: 3,
    productBrand: "Puma",
    productDetail: "Supertec Running Shoes For Men",
    originalPrice: 6900,
    price: 5000,
    discount: 20,
    ratings: 4.9,
    inStock: true,
    fastDelivery: false,
    imgURL: "../assets/exotic.png",
  },
  {
    id: 4,
    productBrand: "Puma",
    productDetail: "Ferrari X-Ray Speed Running Shoes For Men  (White)",
    originalPrice: 3500,
    price: 1700,
    discount: 30,
    ratings: 3.9,
    inStock: true,
    fastDelivery: true,
    imgURL: "../assets/exotic.png",
  },
  {
    id: 5,
    productBrand: "Puma",
    productDetail: "Troy MU Running Shoes For Men (Grey)",
    originalPrice: 4000,
    price: 3300,
    discount: 20,
    ratings: 3.2,
    inStock: true,
    fastDelivery: false,
    imgURL: "../assets/exotic.png",
  },
  {
    id: 6,
    productBrand: "Adidas",
    productDetail: "Runesy M Running Shoes For Men  (Grey) ",
    originalPrice: 1000,
    price: 599,
    discount: 20,
    ratings: 2.0,
    inStock: false,
    fastDelivery: false,
    imgURL: "../assets/exotic.png",
  },
  {
    id: 7,
    productBrand: "Adidas",
    productDetail: "Pictoris M Running Shoes For Men  (Black) ",
    originalPrice: 2000,
    price: 1700,
    discount: 40,
    ratings: 3.0,
    inStock: true,
    fastDelivery: false,
    imgURL: "../assets/exotic.png",
  },
  // {
  //   id: 8,
  //   productBrand: "Adidas",
  //   productDetail: "Adifloss M Running Shoes For Men  (Blue) ",
  //   originalPrice: 5000,
  //   price: 2500,
  //   discount: 50,
  //   ratings: 2.9,
  //   inStock: false,
  //   fastDelivery: false,
  // },
  // {
  //   id: 9,
  //   productBrand: "Adidas",
  //   productDetail: "Quickflow M Running Shoes For Men  (Blue)",
  //   originalPrice: 9000,
  //   price: 8000,
  //   discount: 10,
  //   ratings: 4.9,
  //   inStock: false,
  //   fastDelivery: true,
  // },
  // {
  //   id: 10,
  //   productBrand: "Nike",
  //   productDetail: "Revolution 5 Running Shoes For Men  (Black) ",
  //   originalPrice: 2700,
  //   price: 2200,
  //   discount: 20,
  //   ratings: 2.8,
  //   inStock: false,
  //   fastDelivery: false,
  // },
  // {
  //   id: 11,
  //   productBrand: "Nike",
  //   productDetail: "Revolution 6 Next Nature Road s Running Shoes For Men  ",
  //   originalPrice: 9000,
  //   price: 8400,
  //   discount: 10,
  //   ratings: 4.9,
  //   inStock: true,
  //   fastDelivery: false,
  // },
  // {
  //   id: 12,
  //   productBrand: "Nike",
  //   productDetail: "Downshifter 11 Road s Running Shoes For Men ",
  //   originalPrice: 3000,
  //   price: 2000,
  //   discount: 30,
  //   ratings: 3.5,
  //   inStock: true,
  //   fastDelivery: true,
  // },
  // {
  //   id: 13,
  //   productBrand: "Nike",
  //   productDetail: "Revolution 4 Running Shoes For Men  (Black)",
  //   originalPrice: 7000,
  //   price: 5999,
  //   discount: 20,
  //   ratings: 3.9,
  //   inStock: true,
  //   fastDelivery: false,
  // },
  // {
  //   id: 14,
  //   productBrand: "Nike",
  //   productDetail: "Revolution 6 Next Nature Road Running Shoes",
  //   originalPrice: 5000,
  //   price: 3000,
  //   discount: 50,
  //   ratings: 3.1,
  //   inStock: false,
  //   fastDelivery: true,
  // },
  // {
  //   id: 15,
  //   productBrand: "Reebok",
  //   productDetail: "Downshifter 11 Road s Running Shoes For Men ",
  //   originalPrice: 10000,
  //   price: 9000,
  //   discount: 30,
  //   ratings: 3.5,
  //   inStock: true,
  //   fastDelivery: true,
  // },
  // {
  //   id: 16,
  //   productBrand: "Reebok",
  //   productDetail: "Revolution 4 Running Shoes For Men  (Black)",
  //   originalPrice: 10000,
  //   price: 8999,
  //   discount: 20,
  //   ratings: 3.9,
  //   inStock: true,
  //   fastDelivery: false,
  // },
  // {
  //   id: 17,
  //   productBrand: "Hrx",
  //   productDetail: "Revolution 6 Next Nature Road Running Shoes",
  //   originalPrice: 5000,
  //   price: 10000,
  //   discount: 50,
  //   ratings: 3.1,
  //   inStock: false,
  //   fastDelivery: true,
  // },
];
// export const products = [
//   {
//     _id: uuid(),
//     title: "You Can WIN",
//     author: "Shiv Khera",
//     price: "5000",
//     categoryName: "non-fiction",
//   },
//   {
//     _id: uuid(),
//     title: "You are Winner",
//     author: "Junaid Qureshi",
//     price: "3000",
//     categoryName: "horror",
//   },
//   {
//     _id: uuid(),
//     title: "Think and Grow Rich",
//     author: "Shiv Khera",
//     price: "1000",
//     categoryName: "fiction",
//   },
// ];
